### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by the3plet** [brucellino/hashiatho.me#24]
![image](https://user-images.githubusercontent.com/88719525/197397326-ec95d64d-f138-461b-822b-7850b260d068.png)
It would be better if this would be converted to card, if you i assign me i can make it done.

**Comment by brucellino** [comment]
bring it fam

**Comment by the3plet** [comment]
can you label this as hacktoberfest

**Comment by brucellino** [comment]
Closing this for now. Feel free to re-open if you're still interested.
