### ISSUE TITLE
Modify the header and footer of the website

### ISSUE THREAD

**Issue by SonamGiri9150** [brucellino/hashiatho.me#25]

**Comment by SonamGiri9150** [comment]
I would like to work on this
Please assign me to this task

**Comment by brucellino** [comment]
Hi @SonamGiri9150 thanks for your interest! Can you please give me an idea of what you'd like to change in the header and footer?
Thanks!
Bruce

**Comment by SonamGiri9150** [comment]
I would like to enhance the presentation of the information in the header and maybe add the links to the footer if it's fine

**Comment by brucellino** [comment]
Sounds great, send a PR and we'll discuss it :)

**Comment by brucellino** [comment]
Closing for now. Feel free to re-open if interest re-awakens.
